#! /bin/sh

################################################################################
#                               ...        .     ....   .  .        .
#                           ... | |..     / \   |  . \ | |(.)  ... ( )  ...
#                          / ..|| '  \   / ^ \  | |.) )| || | / ^ \|/  / ..|
#                         | (.. | |^| | / ... \ |  . < | || ||  ../    \.. \
#                          \...||.| |.|/./   \.\|.| \.\|.||.| \...|    |.../
#
########## Charlie's Basic Bspwmrc #############################################

# Startup

  ## Monitor configuration
  if xrandr | grep "VGA1 disconnected"; then
    xrandr --output LVDS1 --auto --primary --output VGA1 --off
    bspc monitor LVDS1 -d 1 2 3 4
  else
    xrandr --output LVDS1 --off --output VGA1 --auto --output HDMI2 --mode 2560x1080_42 --primary --left-of VGA1
    bspc monitor VGA1 -d 5 6 7 8
    bspc monitor HDMI2 -d 1 2 3 4
  fi

  ## Remove all rules before a bspwm restart
  bspc rule -r "*"

  $HOME/.config/sxhkd/launch.sh &
  $HOME/.config/xinputd/launch.sh &
  $HOME/.config/polybar/launch.sh &
  [ ! -s ~/.config/mpd/pid ] && mpd &
  nm-applet &
  feh --bg-scale --no-xinerama "$HOME/.config/wallpaper/current-wallpaper.png" &
  xsetroot -cursor_name left_ptr &
  killall unclutter ; unclutter -b --timeout 3 &
  killall unclutter ; picom -b &


# Basic Settings

  ## Window Settings
  bspc config border_width                        4
  bspc config window_gap                          30
  bspc config top_padding                          -10
  bspc config bottom_padding                      0
  bspc config split_ratio                         0.40
  bspc config normal_border_color                 "#434c5e"
  bspc config active_border_color                 "#5e81ac"
  bspc config focused_border_color                "#8fbcbb"
  bspc config presel_feedback_color               "#81a1c1"
  bspc config borderless_monocle                  true
  bspc config gapless_monocle                     false

  ## Pointer Settings
  bspc config focus_follows_pointer               true
  bspc config pointer_follows_focus               true
  bspc config pointer_modifier                            mod4
  bspc config pointer_action1                             move
  bspc config pointer_action2                             resize_side
  bspc config pointer_action3                             resize_corner

  ## Window rules
  bspc rule -a Gimp state=floating follow=on
  #bspc rule -a firefox desktop='^2'
  bspc rule -a mpv state=floating follow=on
  bspc rule -a KeePassXC state=floating follow=on rectangle=800x600+0+0
  bspc rule -a sxiv state=floating

  ## Scratchpad Settings
  bspc rule -a scratchpad sticky=on locked=on state=floating hidden=on
  [ "$(ps -x | grep -c 'scratchpad')" -lt "3" ] && termite --class scratchpad -e "ncmpcpp" &
  [ "$(ps -x | grep -c 'scratchpad')" -lt "3" ] && termite --class scratchpad -e "$(basename $SHELL)" &
  keepassxc

# Dock/Undocking laptop
## killall -w dockd ; dockd --daemon &
